### ISSUE TITLE
Incoming and outgoing event information in the output from extract_events_transitively_and_group.ceps

### ISSUE THREAD

**Issue by Abhishek2271** [cepsdev/mermaid#2]
Ceps file version: 0.8.1

Currently, extract_events_transitively_and_group.ceps only traverses transitions to extract events within ceps. It would be nice to have it also extract the event information from outside the transitions (like from actions) so that we can then assign directions in the output json.

For example:

Current output:
```
{
  "components":
 [
    {"name":"S1", "events":["E1","E2"]},
    {"name":"S2", "events":["E3","E4","E5"]}
 ]
}
```
Could contain additional info like:

```
{
  "components":
 [
    {"name":"S1", "in_events":["E1","E2"], "out_events":["E3", "E4"]},
    {"name":"S2", "in_events":["E3","E4","E5"], "out_events":["E1", "E2"]}
 ]
}
```

**Comment by cepsdev** [comment]
Feature ready, see [README](README.md). 
A bugfix in ceps-core was necessary, is included in ver. 8.1.1

**Comment by cepsdev** [comment]
Implemented.
